name: Bug Report
about: Report a problem to help us improve
labels: []
title: "[Bug] "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps, commands, inputs, and sample data if applicable.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include full error messages/screenshots/logs).
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/Traces
      description: Paste relevant logs, stack traces, or console output.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, runtime (Node/Python version), browser (if applicable), and any feature flags.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that will help us debug.
    validations:
      required: false
